from . import res_users
# from . import res_partner
from . import nationality
from . import client
from . import lawyer
from . import opposition_lawyer
from . import registrar
from . import secretary
from . import judge
from . import witness
from . import plaintiff
from . import accuse
from . import hr_expense
from . import matter
from . import case
from . import account
from . import law_code
from . import articles
from . import acts
from . import project
from . import matter
from . import case_trail
from . import case_evidance
from . import case_judgement
from . import case_charges
from . import claim
from . import claim_distribution
from . import claim_transaction
from . import disciplinary_observation
from . import penalties
from . import payment_schedule
from . import court
from . import court_admin
from . import case_clerk
from . import defendent